### ISSUE TITLE
zaza should be able to import tests

### ISSUE THREAD

**Issue by gnuoy** [openstack-charmers/zaza#143]
zaza currently ships with all the tests. It would be great if zaza could import the tests from other branches. This would allow other projects to use zaza without having to manage there tests in zaza

**Comment by ChrisMacNaughton** [comment]
Zaza will already load things from packages that are installed in the virtualenv. For example, if I had a package `openstack_charm_tests` that's installed, Zaza's load path magic should happily import tests from `openstack_charm_tests.some.further.path`
