### ISSUE TITLE
No support for applications that move into a standard work load status

### ISSUE THREAD

**Issue by gnuoy** [openstack-charmers/zaza#158]
The tests.yaml allow bespoke workload status statuses and messages to be set. These are mostly useful during a deployment when some intervention is needed to ready the service. Once that action has been run the applications then have standard workload status settings but zaza is still looking for the old ones when assessing readyness.

An example of this is vault which comes up in a state of 'blocked' but once an action has been run goes into a state of 'active'. Any subsequent call to zaza to check application readyness hangs because vault is 'active' not 'blocked'.

**Comment by ChrisMacNaughton** [comment]
This was closed in #159
