### ISSUE TITLE
Enable model.run_on_unit timeout

### ISSUE THREAD

**Issue by thedac** [openstack-charmers/zaza#16]
Currently due to a libjuju  issue #225 [0], the timeout value for model.run_on_unit is disabled. This issue is to remind us to re-enable it once libjuju issue #225 is addressed.

[0] https://github.com/juju/python-libjuju/issues/225

**Comment by n-pochet** [comment]
@thedac , the issue that you are referring to is closed and associated to a merged commit done by @gnuoy.
Furthermore, `model.run_on_unit` is using the timeout value: https://github.com/openstack-charmers/zaza/blob/41a8f7af51afcd255fe86343af9283ae300afaf1/zaza/model.py#L236

**Comment by ChrisMacNaughton** [comment]
This seems to be closed successfully in https://github.com/juju/python-libjuju/pull/237
