### ISSUE TITLE
functest-run-suite --keep-model only keeps last model

### ISSUE THREAD

**Issue by sabaini** [openstack-charmers/zaza#214]
When running tests in several bundles, a new model is autocreated per bundle. 

With the --keep-model flag models should not be destroyed after running tests. However when running multiple bundles only the last one is preserved

**Comment by auria** [comment]
A new flag has been added: `functest-run-suite --keep-all-models` should achieve what you're looking for.

Please confirm. If so, I think this issue can be closed (I can't :))

**Comment by ajkavanagh** [comment]
Agree. Closed via #458
