### ISSUE TITLE
'image-stream': 'daily' is hardcoded

### ISSUE THREAD

**Issue by nobuto-m** [openstack-charmers/zaza#245]
As far as I see, Zaza creates a model with the following model-config and doesn't have a way to override it.
https://github.com/openstack-charmers/zaza/blob/d66f93a6900a4d672a142082f2e5ad957ea08709/zaza/charm_lifecycle/prepare.py#L28-L40

Those values are sane to me, but I was hit by a corner case that a daily image didn't properly come up on a specific provider and wanted to override it to use a known-to-work image with "released" stream instead. It might be a good idea to allow overriding model-configs in some places like `tests/tests.yaml`.

**Comment by nobuto-m** [comment]
Ah, I will try this one to see it works:
https://zaza.readthedocs.io/en/latest/runningcharmtests.html#environment-variables

**Comment by nobuto-m** [comment]
```
$ export MODEL_SETTINGS='image-stream=released'
$ functest-prepare
```
works. But it doesn't work with tox because it doesn't pass environment variables.
https://tox.readthedocs.io/en/latest/example/basic.html#passing-down-environment-variables

So I think it's still nice-to-have of having a way to override with Zaza.

**Comment by ajkavanagh** [comment]
You can ask tox to pass the environment variable using the `passenv = ` directive:

e.g.

```
[testenv]
setenv = ...
install_comand = ...
commands = stestr run {posargs}
passenv = HOME TERM CS_API_* MODEL_SETTTINGS
```

Might this work for you?

**Comment by nobuto-m** [comment]
Yeah, editing tox.ini would also work. I was thinking about what would be the best path for my (kind of corner) use case. It seems activating venv and execute the two lines below as documented is the best.
```
$ export MODEL_SETTINGS='image-stream=released'
$ functest-prepare
```

Because this time is a manual execution of Zaza tests instead of CI, and one-off modification which I don't want to commit in VCS as tox.ini or tests/tests.yaml as a persistent value. So I'm closing this.
