### ISSUE TITLE
models need to be in test mode and have hook retries disabled

### ISSUE THREAD

**Issue by ryan-beisner** [openstack-charmers/zaza#33]
Models which are created by Zaza should enable test mode, to prevent artificially ticking metrics in the charm store for charm usage.

The Zaza models should also disable retrying failed hooks, as we expect all charms to never enter a hook error state.  The retry failed hooks feature is useful for users, but we do want to bail and fail if a charm ever enters an error state in a hook.

```
test-mode: true
transmit-vendor-metrics: false
automatically-retry-hooks: false
```

These, and other useful tuning from OSCI are here for example:

https://github.com/openstack-charmers/charm-test-infra/blob/master/juju-configs/model-default-serverstack.yaml

https://github.com/openstack-charmers/charm-test-infra/blob/master/juju-configs/controller-default.yaml

**Comment by ChrisMacNaughton** [comment]
This raises an interesting question regarding controller creation given that I don't think Zaza has any support for bootstrapping a controller. *Should* Zaza grow support for bootstrapping a controller in addition to a model?
