### ISSUE TITLE
functest-run-suite missing a path argument

### ISSUE THREAD

**Issue by ryan-beisner** [openstack-charmers/zaza#378]
The ```functest-run-suite``` command assumes tests/bundles/* and tests/tests.yaml.

However, some users have compelling reasons to use other directory structures beyond the tests/ dir.

In those cases, there is no clear way to specify relative charm path to "this" charm.

Zaza should implement an optional base path argument to allow users to declare the location of the directory containing tests.yaml.

### Other observations (workaround)

It is currently possible to achieve the following directory structure example, although the relative path specified in the bundle is not accurate.

#### Ex. Alternate Dir Structure:
tests/functional/tests/tests.yaml
tests/functional/tests/bundles/*

#### Modified tox.ini
Take note of the changedir directive.  Based on the behavior observed below, this should not be used except as a near-term work-around.  The better/longer-term solution, IMHO, is to add a path arg feature to functest-run-suite.

```
[testenv:func]
changedir = {toxinidir}/tests/functional
basepython = python3
commands =
    functest-run-suite --keep-model
```

#### Bundle relative charm
I think this is evidence of an assumptive dir structure in Zaza.

Logically, the user might try "charm: ../../../" because that would be absolutely correct from the perspective of the bundle.yaml file.

But what has to happen, is the user has to specify the wrong charm path ("charm: ../../") as if they had used the assumed dir structure of tests/tests.yaml.  Then, it deploys/tests OK.

**Comment by AurelienLourot** [comment]
Implemented by #380
