### ISSUE TITLE
Allow placing tests.yaml in a different location

### ISSUE THREAD

**Issue by Vultaire** [openstack-charmers/zaza#380]
**Summary: Can we have the location of tests.yaml be customizable in some way, rather than hard-coded to ./tests/tests.yaml?**

----

During charm reworks ongoing right now, my team is trying to reorganize its unit and functional tests like this:

```
<charm-root>/src/tests/unit/
<charm-root>/src/tests/functional/
# Zaza run from <charm-root>/src/
```

Because the tests/tests.yaml location is hard-coded, this results in either a functional testing file being placed outside of where we'd like our functional tests to live:

```
<charm-root>/src/tests/unit/
<charm-root>/src/tests/functional/
<charm-root>/src/tests/tests.yaml
# Zaza run from <charm-root>/src/
```

Or it results in a redundant "tests" directory within tests/functional and requires us to "cd" into that directory before running zaza:

```
<charm-root>/src/tests/unit/
<charm-root>/src/tests/functional/tests/  # functional tests live here under the redundant tests/ subdir.
<charm-root>/src/tests/functional/tests/tests.yaml
# Zaza run from <charm-root>/src/tests/functional/
```

If we opt for the lattern pattern to avoid having our tests.yaml outside the functional test dir, then it also becomes more difficult to have shared test code.  One charm I was working on today ended up using this pattern:

```
<charm-root>/src/tests/unit/
<charm-root>/src/tests/shared/
<charm-root>/src/tests/functional/tests/  # functional tests live here under the redundant tests/ subdir.
<charm-root>/src/tests/functional/tests/tests.yaml
<charm-root>/src/tests/functional/tests/shared  # symlink to src/tests/shared/ to allow for "tests.shared.*"-style imports
# Zaza run from <charm-root>/src/tests/functional/
```

None of the above seem ideal.  It seems like it would be better to allow for tests.yaml to be placed in a different location in some way (env variable, command line arg, doesn't matter), thus allowing us to achieve the structure we would like to have:

```
# Desired structure (not possible today)
<charm-root>/src/tests/unit/
<charm-root>/src/tests/functional/
<charm-root>/src/tests/functional/tests.yaml
# Zaza run from <charm-root>/src/
```

**Comment by gnuoy** [comment]
I think this is a duplicate of #378 . Either way I have a wip that hopefully does what you need https://github.com/openstack-charmers/zaza/pull/381

**Comment by Vultaire** [comment]
Agreed; didn't catch #378 and glad to hear about the WIP patch.  Thanks!
