### ISSUE TITLE
retry zaza get_status() and async_wait_for_applications_status() if python-libjuju disconnects

### ISSUE THREAD

**Issue by ajkavanagh** [openstack-charmers/zaza#402]
It seems that libjuju can disconnect with the following type of error:

```
04:27:42   File "/var/lib/jenkins/tools/0/charm-test-infra/.tox/clients/lib/python3.5/site-packages/zaza/model.py", line 1136, in async_wait_for_application_states
04:27:42     timeout=timeout)
04:27:42   File "/var/lib/jenkins/tools/0/charm-test-infra/.tox/clients/lib/python3.5/site-packages/juju/model.py", line 720, in block_until
04:27:42     raise websockets.ConnectionClosed(1006, 'no reason')
04:27:42 websockets.exceptions.ConnectionClosed: WebSocket connection is closed: code = 1006 (connection closed abnormally [internal]), reason = no reason
```

i.e. something timed out / dropped the connection to the controller when trying to get status on what is happening.  The annoying this is that this would 'correct' if tried again.  It causes the whole test to fail whereas it's just a comms error to the controller.

We should **definitely** try to work around this as we are wasting resources on failing tests that would otherwise just pass as the test couldn't get the status just 'once' during a several hours long test.

**Comment by AurelienLourot** [comment]
Workaround merged
