### ISSUE TITLE
Printing of log excerpt from unit in error may be confusing

### ISSUE THREAD

**Issue by fnordahl** [openstack-charmers/zaza#417]
One use case for Zaza is to functionally test a single charm. To functionally test a charm you most likely need to construct a bundle containing other charms that act as "test fixtures" for your charm test. When Zaza deploys the bundle it will detect if any of the charms enter `error` state and stop the deployment.

To be helpful Zaza also reaches out to the unit in error and retrieves a log excerpt from it.

While this in itself is a great time saver and gives the developer a opportunity to immediately get a hint of what the problem might be, it may also be a source of confusion.

In its current form you may be fooled to think that the error printed in the log comes from the charm under test, while in reality it comes from some random other charm in the bundle/model. In a stressed moment we experienced making a bad decision on the back of this.

A simple fix might be to just prefix every line of the log output with the unit name from which the log output comes from.

**Comment by ajkavanagh** [comment]
> A simple fix might be to just prefix every line of the log output with the unit name from which the log output comes from.

Huge +1 on this; this is such a simple fix that it seems "obvious" that it should have been done from the start :)
