### ISSUE TITLE
The behavior of model.run_on_unit has been changed to run only actions

### ISSUE THREAD

**Issue by rgildein** [openstack-charmers/zaza#649]
The [`async_run_on_unit`](https://github.com/openstack-charmers/zaza/blob/c44d35940d4cb32a2b0b3b0d82eced728c2fafc4/zaza/model.py#L556) function was changed (by [commit](https://github.com/openstack-charmers/zaza/commit/3e7b2a5ec74b2ada7a2c2286ef57b31f5c0eac53)) to wait for actions and like this is no longer possible to run command with it.
I'm not sure if there's any way to fix this, but I'd at least suggest renaming the command parameter to action.

**Comment by agileshaw** [comment]
It seems that [this](https://github.com/openstack-charmers/zaza/commit/3e7b2a5ec74b2ada7a2c2286ef57b31f5c0eac53#diff-6c1c4f815766d1a7babc949ac57bf3b6881d8760b2abe602359b35d4acf805c3R573) is the line where running command instead of action hangs.

**Comment by ajkavanagh** [comment]
@rgildein it's probably that actions on Juju 3.x wait by default, whereas on Juju 2.x they didn't.  Maybe this has been propagated to libjuju aswell?  (i.e. Juju 3.x `run` needs the `--background` flag to have the same behaviour as Juju 2.x. `run-action`).

**Comment by wolsen** [comment]
This should be fixed with the above PR being merged. Please re-open if not.

**Comment by rgildein** [comment]
I can confirm that it's working now.

@ajkavanagh the libjuju 2.9 is by [default waiting](https://github.com/juju/python-libjuju/blob/f28a5917b5ae1f6fe9ab720ed0f370a02ddf0c23/juju/unit.py#L173) if you are using `run`, but in libjuju 3.1 you need to [provide block=True](https://github.com/juju/python-libjuju/blob/228922c46650a954df26fe3c4a97e95f832d0539/juju/unit.py#L240-L241) or wait yourself.
